# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'File Sharing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FileExplorer',
       :git => 'https://github.com/anismansuri63/FileExplorer.git',:branch => 'dev-swift-5.0'

end
